### ISSUE TITLE
background execution problem

### ISSUE THREAD

**Issue by Apon77** [rokibhasansagar/slimhub_actions#4]
When i try to download the script, and run as 
`chmod +x cleanup.sh && ./cleanup.sh &`
then after sometimes, it stops running. Probably before homebrew removing,,

any way to fix it??

Thanks

**Comment by rokibhasansagar** [comment]
I'm not seeing any error on my end.
To further investigate, I have to look at your script and log output to figure out the actual problem.

**Comment by Apon77** [comment]
> I'm not seeing any error on my end.
> To further investigate, I have to look at your script and log output to figure out the actual problem.

ops! I just noticed that I was using your previous script, which was only compatible with ubuntu 20.04 ig. will check with the latest script and report. Sorry for inconvenience.

**Comment by Apon77** [comment]
> I'm not seeing any error on my end.
> To further investigate, I have to look at your script and log output to figure out the actual problem.

It's still happening. 
how to reproduce:
connect ssh to actions, then
`wget https://raw.githubusercontent.com/rokibhasansagar/slimhub_actions/main/cleanup.sh && chmod +x cleanup.sh && ./cleanup.sh &`

Then I ran some other commands like htop, echo hello world, then closed the tmate session. then when I reconnect to the session and used the jobs command to see background jobs it is said stopped jobs. 

`~$ jobs
[1]+  Stopped                 ./cleanup.sh
`

Btw it's working fine if I use it as an action with -uses steps. But it consumes 8-10 minutes. I just wished if this 8-10 minutes can be done in the background.

Thanks.

**Comment by rokibhasansagar** [comment]
Maybe closing the tmate session was stopping the script 😕 

Try running like this -
```bash
repo init args opts ..
curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash &>/dev/null & disown;
repo sync args opts ..
```

**Comment by Apon77** [comment]
> Maybe closing the tmate session was stopping the script 😕
> 
> Try running like this -
> 
> ```shell
> repo init args opts ..
> curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash &>/dev/null & disown;
> repo sync args opts ..
> ```

It worked! Thanks brother ❤️
